apiVersion: v1
kind: Pod
metadata:
  name: configmap1
spec:
  containers:
  - name: myapp-container
    image: alpine
    command: ['sh', '-c', "watch echo Nivel de verbose: $(VERBOSE)"]
    env:
    - name: VERBOSE
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: verbose
