apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset3
spec:
  replicas: 2
  selector:
   matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
