apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: rgpd-policy
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: internal
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      name: rgpd
  policyTypes:
  - Ingress
