apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Datos desde el helper de Debian > /pod-data/index.html && sleep 3600"]

  volumes:
  - name: shared-data
