apiVersion: v1
kind: Service
metadata:
  name: nginx-external
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30180
      name: http
    - port: 443
      nodePort: 31443
      name: https
  selector:
    app: my-nginx
